package com.olexyn.ensync.artifacts;

public enum OpsResultType {
    IGNORE_COPY_SAME_AGE,
    IGNORE_COPY_OTHER_IS_NEWER,
    IGNORE_COPY_NOT_A_FILE,
    IGNORE_COPY_COULD_NOT_HASH,
    IGNORE_DELETE_OTHER_NOT_FOUND,
    IGNORE_DELETE_OTHER_IS_NEWER,
    OK_DROPPED_AGE_FROM,
    OK_DROPPED_AGE_TO,
    OK_COPY,
    OK_DELETE,
    WARN_COULD_NOT_CREATE_PARENT,
    WARN_COULD_NOT_COPY,
    WARN_COULD_NOT_DELETE
}
